"""Create user table

Revision ID: 54e953fd60ae
Revises: 
Create Date: 2026-09-02 16:55:48.227765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '54e953fd60ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('ATTENDEE', 'ORGANIZER', 'ADMIN', 'SUPER_ADMIN', name='user_role'), server_default='ATTENDEE', nullable=False),
    sa.Column('last_known_lat', sa.Float(), nullable=True),
    sa.Column('last_known_lng', sa.Float(), nullable=True),
    sa.Column('last_location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('home_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_permission_granted', sa.Boolean(), nullable=False),
    sa.Column('preferred_radius_km', sa.Float(), nullable=False),
    sa.Column('notification_opt_in', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
